// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 367895185124811901),
      name: 'TokenAccount',
      lastPropertyId: const IdUid(3, 1925580729938508010),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 5514816993674192479),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 7478045628579603506),
            name: 'pubkey',
            type: 9,
            flags: 2080,
            indexId: const IdUid(1, 39974764581534326)),
        ModelProperty(
            id: const IdUid(3, 1925580729938508010),
            name: 'mint',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(2, 5266863703261087996),
      name: 'TokenAccountBalance',
      lastPropertyId: const IdUid(5, 7780579752845648923),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 6370121777070919057),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 3390916009822493583),
            name: 'pubkey',
            type: 9,
            flags: 2080,
            indexId: const IdUid(2, 3179261069626181659)),
        ModelProperty(
            id: const IdUid(3, 2214709321243468957),
            name: 'amount',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 7841246826561656506),
            name: 'decimals',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 7780579752845648923),
            name: 'uiAmountString',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(3, 7974835637137839539),
      name: 'TransactionInfo',
      lastPropertyId: const IdUid(8, 8529011510807625140),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 3906413573074305648),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 7489408164910114067),
            name: 'signature',
            type: 9,
            flags: 2080,
            indexId: const IdUid(3, 7619057542350705085)),
        ModelProperty(
            id: const IdUid(3, 8108121278055401915),
            name: 'slot',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 7818928450910145281),
            name: 'err',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 695262653606115043),
            name: 'memo',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 653477521075791061),
            name: 'blockTime',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 90772329218947775),
            name: 'transactionDetails',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 8529011510807625140),
            name: 'dbConfirmationStatus',
            type: 6,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(3, 7974835637137839539),
      lastIndexId: const IdUid(3, 7619057542350705085),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    TokenAccount: EntityDefinition<TokenAccount>(
        model: _entities[0],
        toOneRelations: (TokenAccount object) => [],
        toManyRelations: (TokenAccount object) => {},
        getId: (TokenAccount object) => object.id,
        setId: (TokenAccount object, int id) {
          object.id = id;
        },
        objectToFB: (TokenAccount object, fb.Builder fbb) {
          final pubkeyOffset =
              object.pubkey == null ? null : fbb.writeString(object.pubkey!);
          final mintOffset =
              object.mint == null ? null : fbb.writeString(object.mint!);
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, pubkeyOffset);
          fbb.addOffset(2, mintOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = TokenAccount(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              pubkey: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 6),
              mint: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 8));

          return object;
        }),
    TokenAccountBalance: EntityDefinition<TokenAccountBalance>(
        model: _entities[1],
        toOneRelations: (TokenAccountBalance object) => [],
        toManyRelations: (TokenAccountBalance object) => {},
        getId: (TokenAccountBalance object) => object.id,
        setId: (TokenAccountBalance object, int id) {
          object.id = id;
        },
        objectToFB: (TokenAccountBalance object, fb.Builder fbb) {
          final pubkeyOffset =
              object.pubkey == null ? null : fbb.writeString(object.pubkey!);
          final amountOffset =
              object.amount == null ? null : fbb.writeString(object.amount!);
          final uiAmountStringOffset = object.uiAmountString == null
              ? null
              : fbb.writeString(object.uiAmountString!);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, pubkeyOffset);
          fbb.addOffset(2, amountOffset);
          fbb.addInt64(3, object.decimals);
          fbb.addOffset(4, uiAmountStringOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = TokenAccountBalance(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              pubkey: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 6),
              amount: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 8),
              decimals: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 10),
              uiAmountString: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12));

          return object;
        }),
    TransactionInfo: EntityDefinition<TransactionInfo>(
        model: _entities[2],
        toOneRelations: (TransactionInfo object) => [],
        toManyRelations: (TransactionInfo object) => {},
        getId: (TransactionInfo object) => object.id,
        setId: (TransactionInfo object, int id) {
          object.id = id;
        },
        objectToFB: (TransactionInfo object, fb.Builder fbb) {
          final signatureOffset = object.signature == null
              ? null
              : fbb.writeString(object.signature!);
          final errOffset =
              object.err == null ? null : fbb.writeString(object.err!);
          final memoOffset =
              object.memo == null ? null : fbb.writeString(object.memo!);
          final transactionDetailsOffset = object.transactionDetails == null
              ? null
              : fbb.writeString(object.transactionDetails!);
          fbb.startTable(9);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, signatureOffset);
          fbb.addInt64(2, object.slot);
          fbb.addOffset(3, errOffset);
          fbb.addOffset(4, memoOffset);
          fbb.addInt64(5, object.blockTime);
          fbb.addOffset(6, transactionDetailsOffset);
          fbb.addInt64(7, object.dbConfirmationStatus);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = TransactionInfo(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              signature: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 6),
              slot: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 8),
              err: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 10),
              memo: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12),
              blockTime: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 14),
              transactionDetails: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 16))
            ..dbConfirmationStatus = const fb.Int64Reader()
                .vTableGetNullable(buffer, rootOffset, 18);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [TokenAccount] entity fields to define ObjectBox queries.
class TokenAccount_ {
  /// see [TokenAccount.id]
  static final id =
      QueryIntegerProperty<TokenAccount>(_entities[0].properties[0]);

  /// see [TokenAccount.pubkey]
  static final pubkey =
      QueryStringProperty<TokenAccount>(_entities[0].properties[1]);

  /// see [TokenAccount.mint]
  static final mint =
      QueryStringProperty<TokenAccount>(_entities[0].properties[2]);
}

/// [TokenAccountBalance] entity fields to define ObjectBox queries.
class TokenAccountBalance_ {
  /// see [TokenAccountBalance.id]
  static final id =
      QueryIntegerProperty<TokenAccountBalance>(_entities[1].properties[0]);

  /// see [TokenAccountBalance.pubkey]
  static final pubkey =
      QueryStringProperty<TokenAccountBalance>(_entities[1].properties[1]);

  /// see [TokenAccountBalance.amount]
  static final amount =
      QueryStringProperty<TokenAccountBalance>(_entities[1].properties[2]);

  /// see [TokenAccountBalance.decimals]
  static final decimals =
      QueryIntegerProperty<TokenAccountBalance>(_entities[1].properties[3]);

  /// see [TokenAccountBalance.uiAmountString]
  static final uiAmountString =
      QueryStringProperty<TokenAccountBalance>(_entities[1].properties[4]);
}

/// [TransactionInfo] entity fields to define ObjectBox queries.
class TransactionInfo_ {
  /// see [TransactionInfo.id]
  static final id =
      QueryIntegerProperty<TransactionInfo>(_entities[2].properties[0]);

  /// see [TransactionInfo.signature]
  static final signature =
      QueryStringProperty<TransactionInfo>(_entities[2].properties[1]);

  /// see [TransactionInfo.slot]
  static final slot =
      QueryIntegerProperty<TransactionInfo>(_entities[2].properties[2]);

  /// see [TransactionInfo.err]
  static final err =
      QueryStringProperty<TransactionInfo>(_entities[2].properties[3]);

  /// see [TransactionInfo.memo]
  static final memo =
      QueryStringProperty<TransactionInfo>(_entities[2].properties[4]);

  /// see [TransactionInfo.blockTime]
  static final blockTime =
      QueryIntegerProperty<TransactionInfo>(_entities[2].properties[5]);

  /// see [TransactionInfo.transactionDetails]
  static final transactionDetails =
      QueryStringProperty<TransactionInfo>(_entities[2].properties[6]);

  /// see [TransactionInfo.dbConfirmationStatus]
  static final dbConfirmationStatus =
      QueryIntegerProperty<TransactionInfo>(_entities[2].properties[7]);
}
